### ISSUE TITLE
skills/pyproject.toml testpaths is fail-open: 25 test dirs unlisted, ~1161 tests invisible to CI, 23 failing

### ISSUE THREAD

**Issue by jankneumann** [jankneumann/agentic-coding-tools#345]
## Summary

`skills/pyproject.toml`'s `testpaths` is a hand-maintained enumeration. CI's
`test-infra-skills` job runs a bare `uv run pytest` from `skills/`, which honours
it — so any directory missing from the list is silently not run, and CI is green
either way.

**25 of the directories under `skills/tests/` are unlisted**, hiding **102 test
files / ~1161 tests**. Running them per-directory, **23 currently fail.**

## Measurements

Taken on `openspec/trace-requirements-to-contracts` @ `147e2807`.

| | |
|---|---|
| `testpaths` entries listed | 36 |
| `skills/tests/*` dirs with tests but unlisted | **25** |
| Invisible test files | **102** |
| Invisible tests | **~1161** |
| Invisible **failures** | **23** |

Failing dirs, run in isolation:

```
tests/autopilot                  7 failed, 209 passed   (23 files)
tests/playwright-validator       6 failed,  63 passed
tests/phase-record-compaction    5 failed, 164 passed
tests/docs                       3 failed,   5 passed
tests/agent-coordinator          2 failed,  38 passed
```

`tests/autopilot` being unlisted is the sharpest instance: the orchestrator that
drives every plan/implement/validate run in this repo has 216 tests, none of
which CI executes.

The other 20 unlisted dirs are green in isolation: `archive-roadmap`,
`autopilot-roadmap`, `coordinator-task-status-renderer`, `githooks`,
`integration`, `iterate-on-plan`, `langfuse`, `merge-pull-requests`,
`plan-roadmap`, `prioritize-proposals`, `prototype-feature`, `quick-task`,
`refresh-architecture-contracts`, `review-artifacts`, `roadmap-runtime`,
`session-bootstrap`, `session-log`, `vendor-neutral-autopilot`, `worktree`,
`validate-feature` (now fixed, see below).

## This cannot be fixed by pasting 25 lines in

Collecting all 25 together produces **13 collection errors** that do not occur
per-directory:

```
ImportError: cannot import name 'Checkpoint' from 'models'
  (skills/project-context-runtime/scripts/models.py)
```

Several skills each ship a flat top-level `scripts/models.py`; whichever lands on
`sys.path` first wins for the whole session. Affected: `archive-roadmap`,
`autopilot-roadmap` (3), `plan-roadmap` (3), `playwright-validator` (2),
`roadmap-runtime` (4). **The shadowing has to be solved before the paths can be
registered**, or `test-infra-skills` goes red on collection.

## Root cause

`git log -L '/testpaths/,+6:skills/pyproject.toml'`:

```
f3674ef6  testpaths = ["tests"]           <- catch-all glob
3f369651  testpaths = [ "worktree/…", … ] <- #41 converted it to an explicit list
```

Converting a catch-all into a hand-maintained registry moved the failure mode
from "picks up junk" to "silently drops the new thing" — and the second produces
a *passing* CI run, so nothing surfaces it.

**This has already happened at least twice before and was fixed instance-by-
instance rather than structurally.** The list contains its own tombstone:

> `coordination-bridge/scripts/tests` (the in-skill legacy dir) was already
> listed, but `tests/coordination-bridge` was not — so everything there,
> including the pre-existing test_archetype_resolve.py, was invisible to the
> default CI sweep. A test CI never runs fails the same way as one that always
> passes.

Someone hit this, wrote the lesson down, and did not fix the mechanism.

## Proposed remediation

1. **Add a meta-test** asserting every `skills/tests/<dir>` containing `test_*.py`
   appears in `testpaths`. This is the actual fix — it converts a fail-open
   registry into a fail-closed one, and it is what stops instance #4. It should
   land with an explicit allow-list for intentional exclusions, so "not listed"
   always means "deliberately excluded", never "forgotten".
2. **Resolve the flat-module shadowing** — the `scripts/models.py` collision
   across the roadmap-family skills. Related prior art: pytest namespace-package
   shadowing needs `__init__.py` in test dirs.
3. **Register the 20 green dirs** once (2) lands.
4. **Triage the 23 failures** in the 5 red dirs, registering each dir as it goes
   green. Do NOT register them red — a permanently-red required job trains people
   to ignore it, which is the same fail-open in a different costume.

Order matters: (1) first, so the problem stops growing while (2)–(4) are done.

## Already fixed

`tests/validate-feature` (1 file, 5 tests, all passing) was registered on
`openspec/trace-requirements-to-contracts` as task 5.7b, because that change
depends on it. Verified bare from `skills/`: `pytest --collect-only -q | grep -c
'^tests/validate-feature/'` gives 5 with the entry, 0 without, 5 after restore.
Full bare suite with it: 2350 passed. **The remaining 24 are this issue.**

## Why this matters more than the raw count

This repo's whole review apparatus is built on the premise that a green check
means something. A test directory CI never collects and a gate that cannot fail
are the same defect — they both produce an unfalsifiable green. That is
precisely the class of failure `trace-requirements-to-contracts` exists to
eliminate for contracts, and it is currently live in the test harness itself.
